excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://galantai.github.io
title: galantai
tagline: kavicsaritmetika
description: matematika és határterületei (jobb esetben máshogy)
paginate: 5